# Project information
site_name: servicegenerator
site_url: https://nickyklaus.github.io/servicegenerator/
site_author: Nikolai Beloglazov
site_description: Maven plugin for generating Java microservices based on AST of the sources

# Repository
repo_name: nickyklaus/servicegenerator
repo_url: https://github.com/nickyklaus/servicegenerator

# Copyright
copyright: Copyright &copy; 2022 Nikolai Beloglazov

theme:
  name: material
  custom_dir: overrides

  favicon: /assets/images/favicon.png

  font:
    text: Roboto
    code: Roboto Mono

  palette:
    scheme: default


  # Static files
  static_templates:
    - 404.html

  language: en

  features:
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NickyKlaus
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/nickyklaus

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - meta
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables


# Page tree
nav:
  - Home: index.md
  - User Guide:
      - That was its name: that-was-its-name.md
      - Walking through the jungle: walking-through-the-jungle.md
      - Context is for Kings: context-is-for-kings.md
      - All you need is POM: all-you-need-is-pom.md
      - servicegenerator. Inside out: inside-out.md

extra_css:
  - stylesheets/extra.css