package com.home.servicegenerator.plugin.processing.container.scanner;

import com.github.javaparser.ast.CompilationUnit;
import com.home.servicegenerator.plugin.processing.ProcessingUnit;
import org.apache.maven.plugin.MojoFailureException;

import java.util.List;

/**
 * Scanner for service stub generated by Swagger Codegen.
 *
 * Used before schemas processing.
 *
 * @deprecated will be removed soon (use separate processing schema instead)
 * @see com.home.servicegenerator.plugin.processing.configuration.schema.InternalProcessingSchema
 */
@Deprecated
public interface Scanner {
    List<CompilationUnit> scanController() throws MojoFailureException;
    List<CompilationUnit> scanModel() throws MojoFailureException;
    List<CompilationUnit> scanConfiguration() throws MojoFailureException;

}
