package com.home.origami.plugin.processing.configuration.context.properties;

public enum PropertyName {
    PIPELINE_ID,
    PIPELINE,
    DB_TYPE,
    REPOSITORY_ID_CLASS_NAME,
    REPOSITORY_NAME,
    REPOSITORY_PACKAGE_NAME,
    ABSTRACT_SERVICE_NAME,
    ABSTRACT_SERVICE_PACKAGE_NAME,
    ABSTRACT_SERVICE_METHOD_DECLARATION,
    REPOSITORY_METHOD_DECLARATION,
    CONTROLLER_UNIT,
    BASE_PACKAGE,
}
