package com.github.origami.plugin.processing.container.scanner;

import com.github.javaparser.ast.CompilationUnit;
import com.github.origami.plugin.processing.configuration.schema.InternalProcessingSchema;

import org.apache.maven.plugin.MojoFailureException;

import java.util.List;

/**
 * Scanner for service stub generated by Swagger Codegen.
 *
 * Used before schemas processing.
 *
 * @deprecated will be removed soon (use separate processing schema instead)
 * @see InternalProcessingSchema
 */
@Deprecated
public interface Scanner {
    List<CompilationUnit> scanController() throws MojoFailureException;
    List<CompilationUnit> scanModel() throws MojoFailureException;
    List<CompilationUnit> scanConfiguration() throws MojoFailureException;

}
