package com.home.servicegenerator.plugin.processing.context.properties;

public enum PropertyName {
    DB_TYPE,
    REPOSITORY_ID_CLASS_NAME,
    REPOSITORY_NAME,
    REPOSITORY_PACKAGE_NAME,
    ABSTRACT_SERVICE_NAME,
    ABSTRACT_SERVICE_PACKAGE_NAME,
    ABSTRACT_SERVICE_METHOD_DECLARATION,
    REPOSITORY_METHOD_DECLARATION,
}
