name: documentation
on:
  push:
    branches:
      - plugin-dev

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: |
          pip install \ 
            "mkdocs-material"

      - name: Deploy documentation
        run: mkdocs gh-deploy --force
